[package]
name = "jarvis-scan"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
jemallocator = "0.5.4"
memflow = "0.2.3"
pbr = "1.1.1"
rayon = "1.11.0"
rayon-tlsctx = "0.2.0"
scanflow = "0.2.1"
serde = "1.0.219"
serde_json = "1.0.142"
strum = "0.27.2"
strum_macros = "0.27.2"
